# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 320e9e32c626a283bdc7d44a122e7b6a181eba2dec79d9fd3d4f83d5a86f785b0285c9429c1f53d94ea10472ad768194feabb0f49af4665125537edfad5bed04

test:
  secret_key_base: fe9d0296b98aa4e460cc5c8c98ff2142b0a00a52f1abaef118b2b2dc35a9ad9124e4d27ea34d698aa74b53aef76aaf6150b110a11bf85f7dcddd2211bba9de34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
